basePath: /
host: localhost:8000
info:
  contact:
    email: jhon@jhon
    name: Jhon
    url: https://jhon.dev.br
  description: This is a sample server Petstore server.
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: v1
paths: {}
swagger: "2.0"
